version: "3.9"

networks:
  mongo-shard-net:
    driver: bridge

volumes:
  configsvr_data:
  shard1_data:
  shard2_data:

services:
  configsvr:
    image: mongo:7.0.12
    container_name: configsvr
    hostname: configsvr
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all --dbpath /data/db
    ports:
      - "27019:27019"
    volumes:
      - configsvr_data:/data/db
    networks:
      - mongo-shard-net
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  shard1:
    image: mongo:7.0.12
    container_name: shard1
    hostname: shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all --dbpath /data/db
    ports:
      - "27018:27018"
    volumes:
      - shard1_data:/data/db
    networks:
      - mongo-shard-net
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  shard2:
    image: mongo:7.0.12
    container_name: shard2
    hostname: shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020 --bind_ip_all --dbpath /data/db
    ports:
      - "27020:27020"
    volumes:
      - shard2_data:/data/db
    networks:
      - mongo-shard-net
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongos:
    image: mongo:7.0.12
    container_name: mongos
    hostname: mongos
    depends_on:
      - configsvr
      - shard1
      - shard2
    command: mongos --configdb configReplSet/configsvr:27019 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    networks:
      - mongo-shard-net
